version: "3.9"
services:

  db:
    image: mysql
    container_name: db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/db_init.sql
    restart: always
    ports:
      - 3307:3306
    volumes:
        - ./assets/db_init.sql:/data/application/db_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
        - db

  web:
    image: nginx
    build: .
    ports:
      - 8082:8080
    container_name: web
    restart: always
    volumes:
      - ../test01:/usr/share/nginx/html/test01
#        - \\wsl$\Ubuntu\home\olden\www\portal.dev:/usr/share/nginx/html/test001
#        - \\wsl$\Ubuntu\mnt\c\_work\GitHub\test01:/usr/share/nginx/html/test01

    environment:
        - TZ=Europe/Kiev
#    depends_on:
#        - db
    
